name: NorthStar Terraform CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: environments/dev
  TF_IN_AUTOMATION: true

jobs:
  terraform-ci:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::381492225484:role/NorthStarGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color